# Generated by Django 5.2.4 on 2025-08-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profile',
        ),
    ]
